### ISSUE TITLE
Feature request: Provide file hashes in UI and/or RSS feed

### ISSUE THREAD

**Issue by dmolesUC** [CDLUC3/mrt-dashboard#66]
Occasionally we find a batch of files sitting around that were supposed to have gone to Merritt, while on Merritt we find files with similar but not identical filenames. In order to determine whether the files are in fact the same, it would be handy to be able to get the hashes of the files in Merritt without having to download the files.

There are some tricks one can use to get it now, like following the presigned URL redirect chain till we get to the final S3 or MinIO link, sending a range request for zero bytes, and then getting a hash out of the ETag or the X-Amz-Meta-Sha256 header. But especially for large files, it would be handy just to be able to get the hash stored in the Merritt inventory database.

**Comment by elopatin-uc3** [comment]
Hi @dmolesUC – thanks for filing this. I'm going to "move" it over to mrt-doc for prioritization (will close this issue and create a new one there).

**Comment by elopatin-uc3** [comment]
https://github.com/CDLUC3/mrt-doc/issues/318
